SELECT* FROM city;
SELECT* FROM customers;
SELECT* FROM SALES;
SELECT* FROM PRODUCTS;

# REPORTS & DATA ANALYSIS

-- Q1 COFFEE CONSUMERS COUNT 
-- HOW MANY PEOPLE IN EACH CITY ARE ESTIMATED TO CONSUME COFFEE, GIVEN THAT 25% OF THE POPULATION DOES?

SELECT CITY_NAME, round((POPULATION * 0.25)/1000000,2) AS COFFEE_CUSTOMER, CITY_RANK FROM CITY
ORDER BY 2 DESC
LIMIT 5;

-- Q2 TOTAL REVENUE FROM COFFEE SALES
SELECT
	SUM(TOTAL) AS REVENUE
FROM SALES
WHERE
	extract(YEAR FROM SALE_DATE) = 2023
    AND
	EXTRACT(quarter FROM SALE_DATE) = 4;

-- WHAT IS THE TOTAL REVENUE GENERATED FROM COFFEE SALES ACROSS ALL CITIES IN THE LAST QUARTER OF 2023?

SELECT *, 
	extract(YEAR FROM SALE_DATE) AS YR,
	EXTRACT(quarter FROM SALE_DATE) AS QTR
FROM SALES
WHERE
	extract(YEAR FROM SALE_DATE) = 2023
    AND
	EXTRACT(quarter FROM SALE_DATE) = 4;
    
 -- JOIN TABLE CITY, CUSTOMER,SALES AND FIND REVENUE
 SELECT
	CI.CITY_NAME,
	SUM(TOTAL) AS REVENUE
FROM SALES AS S
JOIN customers AS C
ON S.customer_id = C.customer_id
JOIN CITY AS CI
ON CI.city_id = C.city_id
WHERE
	extract(YEAR FROM S.SALE_DATE) = 2023
    AND
	EXTRACT(quarter FROM S.SALE_DATE) = 4
GROUP BY 1
ORDER BY 2 DESC;

-- Q.3 SALES COUNT FOR EACH PRODUCT
-- HOW MANY UNITS OF EACH COFFEE PRODUCT HAVE BEEN SOLD

SELECT P.product_name,
COUNT(S.SALE_ID) AS TOTAL_SALES 
FROM products AS P 
LEFT JOIN SALES AS S
ON S.PRODUCT_ID = P.product_id
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10; 

-- Q.4 AVG SALES AMOUNT PER CITY
-- WHAT IS THE AVG AMOUNT PER CUSTOMER IN EACH CITY?
-- CITY ABD TOTAL SALE
-- NO CX IN EACH THESE CITY

 SELECT
	CI.CITY_NAME,
	SUM(TOTAL) AS REVENUE,
    COUNT(DISTINCT S.customer_id) AS TOTAL_CX,
    ROUND(
			SUM(S.TOTAL)/COUNT(DISTINCT S.customer_id),1) 
            AS AVG_PER_CUSTMORE
FROM SALES AS S
JOIN customers AS C
ON S.customer_id = C.customer_id
JOIN CITY AS CI
ON CI.city_id = C.city_id
GROUP BY 1
ORDER BY 2 DESC;



SELECT  AVG(TOTAL)FROM SALES;